### PR TITLE
It can get lower

### PR DESCRIPTION
**Pull request by PoroCYon**
I fixed the 64-bit binary (you were using 32-bit code and syscall numbers in a 64-bit binary...) while making it a bit smaller (probably violating the ELF standard, but shhh), crunching it down to 944 bytes (xz in LZMA1-mode), and also added a 32-bit version, 1 byte smaller.

~~This can probably get a tiny bit smaller by zeroing out some unneeded fields in the ELF (thus aiding compression)~~, but the largest gain probably lies at messing with the docker image itself. (And I didn't look into the format.)

EDIT: zeroing them out yields 1 byte for the 32-bit version, but nothing for the 64-bit one.

### CODE REVIEW

**Comment by PoroCYon** [comment]
OK, I've looked into the format, it's a tarball with a lot of overhead (so there's probably lots of space to gain there). I threw out some unneeded stuff, but I couldn't test it, as both GNU and BSD tar create archives that are far larger.

**Comment by ianmiell** [comment]
That's what I thought, but I think the tar file format demands that files
start within 4K blocks, hence all the whitespace. Interestingly, reducing

I'm not sure I want to use xz with a funny flag to save a few bytes - there
are still places that don't have access to relatively new compression tools.

**Comment by ianmiell** [comment]
^Interestingly, reducing^Interestingly, reducing the docker tar content by
hand results in an _increase_ in final gzip size. I couldn't work out why
that was.

**Comment by PoroCYon** [comment]
The increased compressed size is probably due to an increase in "randomness" in the file. I guess the file format isn't really made to be used with *really* small files.

xz is available pretty much everywhere -- including CentOS 7, because otherwise it can't unpack RPMs. `--format=lzma` simply changes the compression algorithm to LZMA1, an older one, instead of the default, LZMA2. The difference here is that LZMA1 has much smaller headers, resulting in a smaller file. (For very small files, LZMA2-compression results in slightly *larger* files than gzip, because the headers are so large, even though the algorithm is better.) `--lzma1=...` tweaks compression parameters, just like `--lzma2` does for the normal format. xz isn't the only program with such flags (though, the Busybox version of xz doesn't have these...)

**Comment by ianmiell** [comment]
OK, you persuaded me...

**Pull request merged**
